version: "3"

volumes:
  postgres_data:
  letsencrypt_certs:

services:
  database-fltshr:
    image: postgres:12
    container_name: "database-fltshr"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  backend-fltshr:
    image: pawelzi/backend-fltshr:latest
    container_name: "backend-fltshr"
    depends_on:
      - database-fltshr
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-fltshr:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      APP_LOGIN_SECRET: ${APP_LOGIN_SECRET}
      SPRING_MAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_VERIFY_TOKEN_SECRET: ${EMAIL_VERIFY_TOKEN_SECRET}
  frontend-fltshr:
    image: pawelzi/frontend-fltshr:latest
    container_name: "frontend-fltshr"
  proxy-fltshr:
    image: pawelzi/proxy-fltshr:latest
    container_name: "proxy-fltshr"
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
    depends_on:
      - backend-fltshr
      - frontend-fltshr
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
